name: jnlp-agent-python-hcbm
on:
  push:
    paths:
      - "jnlp-agent-python-hcbm/**"
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          set -eux;
          for file_path in $(git diff --name-only HEAD~ HEAD | grep jnlp-agent-python-hcbm/);
          do
            /usr/bin/docker buildx build --push --no-cache \
              --platform linux/amd64,linux/arm64 \
              --file ${file_path%/*}/Dockerfile \
              --tag ${{ secrets.DOCKERHUB_USERNAME }}/$(dirname $file_path | sed 's / : g') \
              ${file_path%/*}
          done
